apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    run: load-balancer
    color: green
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    run: nginx-green
    color: green
  type: LoadBalancer